import json

# Country to Language Mapping
countries_languages = {
    "Russia": ["Russian"],
    "Paraguay": ["Spanish", "Guarani"],
    "Senegal": ["French"],
    "Sweden": ["Swedish"],
    "Philippines": ["Filipino", "English"],
    "Singapore": ["English", "Malay", "Mandarin", "Tamil"],
    "Malaysia": ["Malay"],
    "Turkey": ["Turkish"],
    "Malawi": ["English", "Chichewa"],
    "Iraq": ["Arabic", "Kurdish"],
    "Germany": ["German"],
    "Cambodia": ["Khmer"],
    "Afghanistan": ["Dari", "Pashto"],
    "Jordan": ["Arabic"],
    "Sudan": ["Arabic", "English"],
    "France": ["French"],
    "Greece": ["Greek"],
    "Sri Lanka": ["Sinhala", "Tamil"],
    "Taiwan": ["Mandarin"],
    "Algeria": ["Arabic", "Berber"],
    "Slovakia": ["Slovak"],
    "Argentina": ["Spanish"],
    "Belgium": ["Dutch", "French", "German"],
    "Angola": ["Portuguese"],
    "Qatar": ["Arabic"],
    "Ecuador": ["Spanish"],
    "Albania": ["Albanian"],
    "Finland": ["Finnish", "Swedish"],
    "Ghana": ["English"],
    "Nicaragua": ["Spanish"],
    "Peru": ["Spanish"],
    "United States": ["English"],
    "India": ["Hindi", "English"],
    "China": ["Mandarin"],
    "Bahamas": ["English"],
    "Belarus": ["Belarusian", "Russian"],
    "Kuwait": ["Arabic"],
    "Malta": ["Maltese", "English"],
    "Somalia": ["Somali", "Arabic"],
    "Chile": ["Spanish"],
    "Puerto Rico": ["Spanish", "English"],
    "Cayman Islands": ["English"],
    "Soviet Union": ["Russian"],
    "Croatia": ["Croatian"],
    "Nigeria": ["English"],
    "Italy": ["Italian"],
    "Lithuania": ["Lithuanian"],
    "Norway": ["Norwegian"],
    "Spain": ["Spanish"],
    "Cuba": ["Spanish"],
    "Denmark": ["Danish"],
    "Bangladesh": ["Bengali"],
    "Iran": ["Persian"],
    "Ireland": ["English", "Irish"],
    "Liechtenstein": ["German"],
    "Thailand": ["Thai"],
    "Morocco": ["Arabic", "Berber"],
    "Panama": ["Spanish"],
    "Hong Kong": ["Cantonese", "English"],
    "Venezuela": ["Spanish"],
    "Ukraine": ["Ukrainian"],
    "Israel": ["Hebrew"],
    "Iceland": ["Icelandic"],
    "West Germany": ["German"],
    "East Germany": ["German"],
    "South Korea": ["Korean"],
    "Palestine": ["Arabic"],
    "Cyprus": ["Greek", "Turkish"],
    "Uruguay": ["Spanish"],
    "Mexico": ["Spanish"],
    "Zimbabwe": ["English", "Shona", "Sindebele"],
    "Georgia": ["Georgian"],
    "Montenegro": ["Montenegrin"],
    "Indonesia": ["Indonesian"],
    "Guatemala": ["Spanish"],
    "Mongolia": ["Mongolian"],
    "Azerbaijan": ["Azerbaijani"],
    "Armenia": ["Armenian"],
    "Syria": ["Arabic"],
    "Saudi Arabia": ["Arabic"],
    "Uganda": ["English", "Swahili"],
    "Namibia": ["English"],
    "Switzerland": ["German", "French", "Italian", "Romansh"],
    "Ethiopia": ["Amharic"],
    "Latvia": ["Latvian"],
    "Jamaica": ["English"],
    "United Arab Emirates": ["Arabic"],
    "Canada": ["English", "French"],
    "Samoa": ["Samoan", "English"],
    "Czech Republic": ["Czech"],
    "Mozambique": ["Portuguese"],
    "Brazil": ["Portuguese"],
    "Kenya": ["English", "Swahili"],
    "Lebanon": ["Arabic"],
    "Slovenia": ["Slovene"],
    "Dominican Republic": ["Spanish"],
    "Japan": ["Japanese"],
    "Botswana": ["English", "Setswana"],
    "Luxembourg": ["Luxembourgish", "French", "German"],
    "New Zealand": ["English", "Māori"],
    "Poland": ["Polish"],
    "Portugal": ["Portuguese"],
    "Australia": ["English"],
    "Cameroon": ["English", "French"],
    "Romania": ["Romanian"],
    "Bulgaria": ["Bulgarian"],
    "Nepal": ["Nepali"],
    "Austria": ["German"],
    "Egypt": ["Arabic"],
    "Kazakhstan": ["Kazakh", "Russian"],
    "Serbia": ["Serbian"],
    "South Africa": ["Afrikaans", "English", "Zulu", "Xhosa"],
    "Burkina Faso": ["French"],
    "Bermuda": ["English"],
    "Colombia": ["Spanish"],
    "Hungary": ["Hungarian"],
    "Pakistan": ["Urdu", "English"],
    "Vatican City": ["Latin", "Italian"],
    "Mauritius": ["English", "French"],
    "United Kingdom": ["English"],
    "Vietnam": ["Vietnamese"],
    "Netherlands": ["Dutch"]
}

# Save to JSON file
json_file_path = "../data/countries_languages.json"
with open(json_file_path, "w", encoding="utf-8") as f:
    json.dump(countries_languages, f, indent=4, ensure_ascii=False)

print(f"JSON file saved as {json_file_path}")